//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Searchengine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicine
    {
        public int medId { get; set; }
        public string medName { get; set; }
        public Nullable<decimal> medPrice { get; set; }
        public string medDescription { get; set; }
        public Nullable<System.DateTime> medExpiryDate { get; set; }
    }
}
